version: '3.5'
services:
  software:
    image: traefik:v1.7.20 
    command: --docker.domain=leejonchapman.com --acme.email=me@leejonchapman.com  --docker.watch --docker.swarmmode 
    networks: 
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./basic_auth:/basic_auth
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 8080
        traefik.backend: "traefik"
        traefik.frontend.rule: "Host:traefik.leejonchapman.com"
        traefik.frontend.auth.basic.usersFile: "/basic_auth"
        traefik.docker.network: "internal"
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    #watchtower:
    #image: v2tec/watchtower
    #command: --interval 900 --label-enable --cleanup
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #labels:
    #  com.centurylinklabs.watchtower.enable: "true"
    #restart: unless-stopped
networks:
  internal:
    name: internal
    external: true
